server:
    port: 8088



spring:
    datasource:
        driver-class-name: ${DRIVER}
        url: ${URL}
        username: ${USER}
        password: ${PASSWD}
# jpa
    jpa:
        properties:
            hibernate: 
                dialect: org.hibernate.dialect.OracleDialect
                show_sql: true
                format_sql: true
                use_sql_comments: true
        hibernate: 
            ddl-auto: update




# spring:
#     datasource:
#         driver-class-name: org.h2.Driver
#         url: jdbc:h2:mem:testdb
#         username: sa
#         password: 
#     h2:
#         console:
#             enabled: true
#         # jpa
# # jpa
#     jpa:
        
#         hibernate: 
#             ddl-auto: none
#         show-sql: true
#         properties:
#             hibernate: 
#                 dialect: org.hibernate.dialect.OracleDialect

# token
jwt:
    secret: ${JWT_SECRET_KEY} 

openApi:
    serviceKey: ${SERVICE_KEY}
    callBackUrl: ${CALLBACKURL}
    dataType: ${TYPE}